<a href="https://colab.research.google.com/github/NavyaSri-2001/Python_Projects/blob/main/Indexing_Slicing_Arithmetic_Operations_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Indexing in Numpy Arrays**

In [1]:
import numpy as np

In [2]:
array1=np.array([10,20,30])
array1[0]

10

In [4]:
array1[-1] #from left side indexing is like 0,1,2 but if we read from right side indexing is like -1, -2, -3 that's why array1[-1] returns first element from right which is 30

30

In [12]:
array2=np.array([[10,20,30],[40,50,60],[70,80,90]])
array2[0,1]

20

In [10]:
array2[0,:] #gives whole first row

array([10, 20, 30])

In [11]:
array2[:,1] #gives whole 2nd column

array([20, 50, 80])

**In 2D arrays by default elements get stored in row major which means first row 1 elements, next 2nd row etc.
Column major means first column 1 elements, next 2nd col etc**

**Slicing in Numpy Arrays**

Slicing is a way to extract a subset of elements from array [start:stop:step]

In [14]:
array1=np.array([1,2,3,4,5,6,7])
print(array1[1:3])#starts from index 1 and goes till end index-1

[2 3]


In [16]:
array1[1:5:2]# skips 1 one element in b/w becoz step is 2

array([2, 4])

In [22]:
array1[-1:-3:-1]#for reverse direction step is necessary else will get error

array([7, 6])

In [23]:
array1[::2]

array([1, 3, 5, 7])

In [25]:
array1[-1:-3:-2]

array([7])

In [26]:
array1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [39]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array2[1,])
print(array2[:,1])
print(array2[1:3,1:3])#rows from index 1 to 2, columns from index 1 to 2
print(array2[1:3,1])
print(array2[1,1:3])
print(array2[1,1:10])#it wont give any error, it just selects elements till last column
print(array2[:,1:3])#takes all rows and column 1 to column 3-1
print(array2[1:3,:2])#takes rows from 1 to 3-1 and columns from 0 to 2-1
print(array2[1:3,1:])

[4 5 6]
[ 2  5  8 11]
[[5 6]
 [8 9]]
[5 8]
[5 6]
[5 6]
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
[[4 5]
 [7 8]]
[[5 6]
 [8 9]]


**Arithmatic operations on numpy arrays**
1. addition
2. subtraction
3. multiplication
4. matrix multiplication
5. division
6. floor division
7. modulo
8. transpose

For arithmatic operations, size of arrays have to be same

In [40]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
x+y

array([[ 6,  8],
       [10, 12]])

In [50]:
print(x*y) #it just multiplies element *element at same position
print(x@y) #matrix multiplication
print(y/x)#division
print(y//x)#division, which gives floor value
print(y**x)#exponentiation or power
print(y%x)#modulo which gives reminder
print(x.transpose())#transpose converts rows to columns

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[5.         3.        ]
 [2.33333333 2.        ]]
[[5 3]
 [2 2]]
[[   5   36]
 [ 343 4096]]
[[0 0]
 [1 0]]
[[1 3]
 [2 4]]
