<a href="https://colab.research.google.com/github/NavyaSri-2001/Python_Projects/blob/main/Sorting_and_Statistical_Operations_on_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sorting 1D and 2D arrays**

In [1]:
import numpy as np

In [23]:
x=np.array([2,7,1])
y=np.sort(x)
z=np.sort(x)[::-1]#sorting in descending order
z2=-np.sort(-x)#z and z2 are same
print(y)
print(z)
print(z2)

[1 2 7]
[7 2 1]
[7 2 1]


In [22]:
x=np.array([[5,8,2],[10,5,9],[4,2,7]])
y=np.sort(x)#by default it sorts row wise or we can write y=np.sort(x,axis=1) both are same
y2=-np.sort(-x)#sorting in descening order
z=np.sort(x,axis=0)#to sort column wise
print(x)
print(y)
print(y2)
print(z)

[[ 5  8  2]
 [10  5  9]
 [ 4  2  7]]
[[ 2  5  8]
 [ 5  9 10]
 [ 2  4  7]]
[[ 8  5  2]
 [10  9  5]
 [ 7  4  2]]
[[ 4  2  2]
 [ 5  5  7]
 [10  8  9]]


In [8]:
y=np.argsort(x)#gives indexes of sorted values
y2=np.argsort(x,axis=1)#y and y2 are same
z=np.argsort(x,axis=0)#column wise sorted values indexes
print(y)
print(y2)
print(z)

[[2 0 1]
 [1 2 0]
 [1 0 2]]
[[2 0 1]
 [1 2 0]
 [1 0 2]]
[[2 2 0]
 [0 1 2]
 [1 0 1]]


In [12]:
x=np.array([[5,8,2],[10,5,9],[4,2,7]])
x.sort()#sorting inplace without using new variable
print(x)

[[ 2  5  8]
 [ 5  9 10]
 [ 2  4  7]]


**Statistical operations on 1D array**

1. max
2. min
3. sum
4. mean
5. median
6. prod
7. var
8. std

In [28]:
x=np.array([3,4,1,2,5,6])
print(np.max(x))
print(np.min(x))
print(np.sum(x))
print(np.mean(x))
print(np.median(x))#sorts the array and gives middle value
print(np.prod(x))#product of values
print(np.var(x))#variance : how distant elements are from mean sqrt((mean-e1)square+(mean-e2)sqaure....)etc
print(np.std(x))#square of variance

6
1
21
3.5
3.5
720
2.9166666666666665
1.707825127659933
