<a href="https://colab.research.google.com/github/NavyaSri-2001/Python_Projects/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy stands for Numerical Python. Used to work with arrays**

In [3]:
import numpy as np
list1=[10,20,30,40]
array1= np.array(list1)
print(array1)
type(array1)

[10 20 30 40]


numpy.ndarray

In [4]:
list1=[10,20.3,30,40]
array1= np.array(list1, dtype=int)
print(array1)

[10 20 30 40]


In [32]:
list1=[10,20,'hello',40]
array1= np.array(list1, dtype='U32')#converts all elements to strings, 'U32' is for strings
print(array1)

['10' '20' 'hello' '40']


In [9]:
array2=np.arange(1,8) #giving range of numbers. It takes from [1-8)
print(array2)

[1 2 3 4 5 6 7]


In [12]:
array3=np.arange(11,17).reshape(2,3) #creating 2D array
print(array3)

[[11 12 13]
 [14 15 16]]


In [16]:
array4=np.zeros((4,2), dtype=int) #creating 2d array of zeros #by default it gives float values, we can give type explicity if we want
print(array4)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [17]:
array5=np.ones(5)
print(array5)

[1. 1. 1. 1. 1.]


In [20]:
list2=[10,20,30,40]
array6=np.array(list2)
print(array6)
array7=np.array(list2).reshape(2,2)
print(array7)

[10 20 30 40]
[[10 20]
 [30 40]]


**Numpy Attributes**
1. ndim #dimension of array
2. shape #rows, columns
3. size #no.of elements in array
4. dtype #data type of elements in array
5.itemsize #memory allocated to each element in bytes depends on dtype of elements

In [22]:
array7.ndim #since it is a 2D array gives 2

2

In [27]:
array7.shape #(rows,columns)

(2, 2)

In [29]:
array8= np.arange(1,10)
array8.shape #9 elemnts,

(9,)

In [30]:
array7.size

4

In [34]:
array7.dtype

dtype('int64')

In [39]:
list3=[10,12,13]
array9=np.array(list3)
array9.dtype

dtype('int64')

In [40]:
array9.itemsize #since dtype is 64 bits, 1 byte=8 bits so itemsize will be 64/8

8

In [37]:
list4=['j','k']
array10=np.array(list4)
array10.dtype

dtype('<U1')

In [41]:
array10.itemsize #here string is 32 bits which means 32/8 which is 4

4