<a href="https://colab.research.google.com/github/NavyaSri-2001/Python_Projects/blob/main/Reshape_Slicing_Ufunc_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
array1=np.linspace(0,5,10)# linspace takes start point, end point, no.of points and given those no.of evenly spaced points as result
array2=np.linspace(0,5,100)
print(array1)
print(array2)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3.53535354 3.58585859
 3.63636364 3.68686869 3.73737374 3.78787879 3.83838384 3.88888889
 3.93939394 3.98

In [8]:
a3=np.ones((2,3), dtype=int)
print(a3)

[[1 1 1]
 [1 1 1]]


In [10]:
np.eye(4, dtype=int) #creating identity matrix, it is a square matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [15]:
print(np.random.rand(5))# generating random numbers from 0-1 uniform distribution
print(np.random.rand())#gives only 1 number b/w 0-1

[0.06395502 0.05921409 0.44749691 0.65472534 0.39573558]
0.32062699148423035


In [19]:
print(np.random.randn(2))#generates random numbers based on standard normal distribution
print(np.random.randn(2,3))

[-1.0167495   0.16978046]
[[-1.19998083  0.61830044  0.42877848]
 [-0.53531962  0.33471675 -0.32485428]]


In [20]:
np.random.randint(1,100,10)#generates 10 random integers b/w 1-99

array([54, 12, 90, 50, 56,  9, 70,  3, 89, 78])

In [25]:
arr=np.arange(25)
print(arr)
#reshaping array
print(arr.reshape(5,5))#size must be same like 25 elements only

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [30]:
ranarr=np.random.randint(1,100,10)
print(ranarr)

[ 2 96 11 52 52 23 70 55 90 35]


In [33]:
print(ranarr.max())
print(ranarr.argmax())#gives index of max number
print(ranarr.argmin())

96
1
0


In [34]:
#if we dont want to type np.random.randint
from numpy.random import randint
randint(2,10)

9

In [39]:
#slicing in numpy arrays
arr=np.arange(0,11)
print(arr)
slice_arr=arr[0:6]
print(slice_arr)
slice_arr[:6]=99
print(slice_arr)
print(arr)#the above step modifies original array also bcoz of memory issues

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5]
[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [41]:
arr=np.arange(0,11)
print(arr)
arr_copy=arr.copy()
print(arr_copy)
arr_copy[:]=100
print(arr_copy)
print(arr)#original array is not changed becoz we created a copy and just modified it

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [45]:
#slicing and indexing in 2D arrays
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2[0][2])
print(arr2[0,2])#both are same
print(arr2[:2,1:])#gives right 2 columns of first 2 rows
print(arr2[:2])#gives first 2 rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[2 3]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [49]:
arr=np.arange(1,11)
print(arr)
bool_arr=arr>5#conditional arrays
print(bool_arr)
print(arr[bool_arr])#we get only those values from arr where bool_arr is true
print(arr[arr<3])#we can do this in a single step

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[1 2]


**ufunc or universal functions in numpy**
There are some universal functions in numpy predefined, if we want to add any additional function to ufunc library we should use frompyfunc(). frompyfunc() takes 3 args, name of func, no.of input args/arrays, no.of output arrays

In [50]:
def myadd(x,y):
  return x+y
myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,2,3],[1,2,3]))

[2 4 6]


In [51]:
print(type(np.add)) #Check if a function is a ufunc

<class 'numpy.ufunc'>


In [52]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc
